### ISSUE TITLE
Live wallpaper: framerate drops over time

### ISSUE THREAD

**Issue by stuartpb** [markusfisch/ShaderEditor#10]
This is a behavior I've noticed on my Nexus 6, even when the phone is plugged in: the framerate of the live wallpaper reduces every 15 seconds or so, by about half each time. The framerate of the UI itself is not affected.

**Comment by markusfisch** [comment]
Very strange. Unfortunately I haven't been able to reproduce this on any of my devices (including a Nexus 4 and 7 among others).

Does the frame rate really decay to below 1 frame after a minute?

I'll try to get my hands on a Nexus 6 the next couple of days to check this out.

**Comment by stuartpb** [comment]
Okay, I just tested this a bit more rigorously by counting the seconds in my head, and it would seem the dropoff is after about 1 minute (possibly exactly 1 minute). So the wallpaper starts at 60 FPS, then after 1 minute it drops to 30 FPS, then after 2 minutes it drops to 15 FPS.

**Comment by markusfisch** [comment]
Mysterious. I don't know about the Nexus 6 for sure, but the live wallpapers used to run at 30 FPS only. I think that is/was a kind of system limitation to keep the UI responsive enough.

Right now, I don't have any idea what may cause this. It sounds like some buffer is getting "full" but I don't see which and why. Will continue to investigate.

**Comment by stuartpb** [comment]
http://stackoverflow.com/questions/28780460/android-gpu-profiling-opengl-live-wallpaper-is-slow suggests:

> Accumulation of render state. Make sure you "glClear" the color/depth/stencil buffers before you start each render pass (although if you are rendering directly to the window surface this is unlikely to be the problem, as state is guaranteed to be cleared every frame unless you set EGL_BUFFER_PRESERVE).

**Comment by markusfisch** [comment]
Interesting read! Actually, glClear() is already invoked on every frame [here](https://github.com/markusfisch/ShaderEditor/blob/master/ShaderEditor/src/main/java/de/markusfisch/android/shadereditor/opengl/ShaderRenderer.java#L214). May be I should clear more than just the color buffer bit...

**Comment by markusfisch** [comment]
This happened because of rounding errors when the time value becomes too big for a mere mediump float.

Should be fixed in master because the time value [wraps early](https://github.com/markusfisch/ShaderEditor/blob/master/ShaderEditor/src/main/java/de/markusfisch/android/shadereditor/opengl/ShaderRenderer.java#L185) now and the (default) shaders try to set the highest precision possible:

```glsl
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif
```

**Comment by stuartpb** [comment]
Awesome!

**Comment by xloem** [comment]
Is the time value still wrapping early?

I am encountering this issue again.  I expect my phone is low-end and does not support highp.

**Comment by markusfisch** [comment]
Just looked it up - I removed that in https://github.com/markusfisch/ShaderEditor/commit/1a28e4fdfffced1d3a842bab84d92dc390b384b9 because the wrapping would occur after 18 hours only.

So that's probably not really your problem. Does your shader compile (and run) if you simply declare precision highp float; without the #ifdef GL_FRAGMENT_PRECISION_HIGH guard like so:

```glsl
precision highp float;
```

**Comment by xloem** [comment]
Well yes, it compiles and runs, but the issue still occurs after a couple minutes.  Soon the apparant fps is very very low.

My phone needs ~1 minute wrap time at most.

**Comment by xloem** [comment]
After continuing work, I eventually got the error 'high precision not supported, instead compiling high precision as medium precision'.

**Comment by markusfisch** [comment]
After investigating the issue, I think it's probably best to do the wrapping in the shader:

```glsl
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#define WRAPPER 60000.
#else
precision mediump float;
#define WRAPPER 10.
#endif

void main() {
	... mod(time, WRAPPER) ...
}
```

First, contrary to results from earlier versions of this issue (https://github.com/markusfisch/ShaderEditor/issues/14 and https://github.com/markusfisch/ShaderEditor/issues/19) wrapping `time` at a value of 60000 did not solve the problem for me. After about 30 seconds (when `time` is ~30.xxx) the [rounding errors](http://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html#680) became very much noticeable. A modulo of 60000 doesn't (and shouldn't) change anything here, so I'm quite puzzled about what actually solved the issue in #14 and #19.

So I checked out Version 2.0.0 (which it was back then) and checked that. No difference. If you like to try and see if it makes any difference to you - I'd really appreciate that - here's the APK (renamed to .zip because GitHub won't accept .apk): [ShaderEditor200.zip](https://github.com/markusfisch/ShaderEditor/files/422838/ShaderEditor200.zip). Rename it back, save it on your phone and open it. This build has another applicationId and does not conflict with your existing installation. It'll appear as "Shader Editor Probe" in your launcher.

But in theory, it can't make a difference because `time` is always well below 60000. I then checked at what value (in my test case) `time` would have to wrap to avoid rounding errors (on mediump) and I arrived at about 10 (which means 10 seconds). Of course, the exact value depends on how `time` is used in a shader but 10 seconds is not very much.

In fact, that's just a tiny fraction of the [guaranteed minimum range](https://www.khronos.org/files/opengles_shading_language.pdf) of a mediump float (-2^14 to 2^14). Now, that means the app could either always wrap `time` at 10 (what makes no sense for highp) or do it only if highp is not available for fragment shaders (what can easily be checked with [glGetShaderPrecisionFormat()](https://developer.android.com/reference/android/opengl/GLES20.html#glGetShaderPrecisionFormat(int, int, int[], int, int[], int)). But that would result in a quite different behaviour from device to device. So I think it's probably best to deal with the issue in the shader itself. This way, the modulo would be transparent and you could choose a value that fits your specific scenario.

Here's the shader I used for testing (shamelessly stolen from [glsl sandbox](http://glslsandbox.com)):

```glsl
precision mediump float;

#define BLU_SPEED 0.8

uniform float time;
uniform vec2 resolution;

void main() {
	vec2 pos = gl_FragCoord.xy/resolution.y;
	pos.x -= resolution.x/resolution.y/2.0;
	pos.y -= 0.5;
	float fx = sin(pos.x*10.0+time*BLU_SPEED+BLU_SPEED*2.0)/4.0;
	float dist = abs(pos.y-fx)*80.0;
	gl_FragColor = vec4(0.5/dist,0.5/dist,1.0/dist,1.0);
}
```

**Comment by stuartpb** [comment]
> In fact, that's just a tiny fraction of the [guaranteed minimum range](https://www.khronos.org/files/opengles_shading_language.pdf) of a mediump float (-2^14 to 2^14).

Actually, if I'm reading this correctly - and I'm not sure that I am - the spec is only saying that the *absolute maximum range of values* for a mediump float is 2^14 to -2^14,, and that the "integer range" - meaning the [range of precisely-representable integers](http://stackoverflow.com/questions/6060406/using-floats-or-doubles-instead-of-ints/6060451#6060451) - is 2^10.

What I *think* this means is that `mediump` floats have a significand precision of ten bits, and an exponent of 4 bits (this is a couple bits smaller than the [IEEE standard 16-bit float](https://en.wikipedia.org/wiki/Half-precision_floating-point_format) - with highp having a similarly-constrained range within 62 bits, I believe this implies they're reserving a few bits for implementation details.)

What *that* means is, while a `mediump` can contain a value *up to* 1024 without losing integral precision (the next increment it will be able to represent is 1026), it can only represent *fractions* for a much smaller range - from 513 to 1024, it'd be wholes, 256 to 512 it'd be halves, 128 to 256 quarters, 64 to 128 eighths, 32 to 16 the largest fractions would be sixteenths. Only values absolutely smaller than 8 are precise to the 1/32, smaller than 4 1/64, smaller than 2 1/128, and only fractions below a whole are precise to 1/256 (2^-8). (Conversely, 1026 to 2048 will jump by twos, 2052 to 4096 by fours, 4104 to 8192 by eights, and 8208 to 16384 by sixteens.)

(EDIT: I just checked the OP, and what I'm about to describe doesn't quite match its figures. I think my count of the powers is off by a couple in one direction or another, either due to the aforementioned misunderstanding of the spec, or my phone's chip eschewing those aforementioned reserved bits and allocating them to fields closer to the IEEE sizes - but the underlying concept, that precision is being lost at early points in time, should be sound regardless of implementation, and may well be true on some other implementation out there.)

This would explain why I was seeing framerates dropping to a choppy ~8fps after about one minute (values above 64 losing precision beyond eighths), and ~16fps after 30 seconds (values above 32 losing precision beyond sixteenths), and why the highest acceptable value you're seeing for wrapping with mediump is 10 (it's only going lower precision than your framerate, if at all, for the two seconds between eight and ten).

**Comment by xloem** [comment]
That's a nice test shader; it shows artifacts fast.  It fails in both the normal and probe editor on my phone.  This can't be resolved inside the shader because the data is already lost to the mediump float uniform, as stuart described.  Floats are only precise near zero.

One solution might be to pass the fractional component of the time (or ms or ns) in a separate uniform from integral seconds.

**Comment by markusfisch** [comment]
@stuartpb Yes, you're right!

The [spec](https://www.khronos.org/files/opengles_shading_language.pdf) says _required minimum ranges_ (4.5.1 Range and Precision and 4.5.2 Precision Qualifiers on page 38/39) because the implementation may use bigger data types. For example, glGetShaderPrecisionFormat() returns a range of -2^15 (-32768) to 2^15 (32768) for a mediump on a Nexus 4 but the spec demands only -2^14 (-16384) to 2^14 (16384).

But the precision remains to be (at least) 2^10 what is the required minimum. The wikipedia article about the [Half-precision floating-point format](https://en.wikipedia.org/wiki/Half-precision_floating-point_format) you mentioned also contains the precision limitations on decimal values (for IEEE 75 binary16). For example, the precision limitation for decimals between 8 and 16 is a fixed interval of 2^−7 (0.0078125) what means `time` would probably be ~7ms off.

So what can we do? Passing the fractional component in a separate uniform (as @xloem proposed) may seem like an option. But the problem is the mediump float *in the shader* won't be able to represent the result. No matter how clever we're going to transfer the components. To demonstrate this, here's a special build of ShaderEditor sporting a `ftime` uniform that holds only the fractional part of time: [ShaderEditorFtime.zip](https://github.com/markusfisch/ShaderEditor/files/425142/ShaderEditorFtime.zip) (again, with a modified applicationId so you won't touch your original installation; it'll show up as "Shader Editor Ftime").

Now, if we use that in the test shader like this:

```glsl
precision mediump float;

#define BLU_SPEED 0.8

uniform float time;
uniform float ftime;
uniform vec2 resolution;

void main() {
	vec2 pos = gl_FragCoord.xy/resolution.y;
	pos.x -= resolution.x/resolution.y/2.0;
	pos.y -= 0.5;
	float fx = sin(pos.x*10.0+floor(time)*BLU_SPEED+ftime*BLU_SPEED+BLU_SPEED*2.0)/4.0;
	float dist = abs(pos.y-fx)*80.0;
	gl_FragColor = vec4(0.5/dist,0.5/dist,1.0/dist,1.0);
}
```

You'll see things get ugly quickly. For the very same reason as before. `fx` is a mediump float.
And that's why I thought this problem could better be solved in the shader. For example, if we wrap `time` at the right value - the exact moment when the wave is where it started, here's an approximation - quality should remain to be the same for all time:

```glsl
precision mediump float;

#define BLU_SPEED 0.8

uniform float time;
uniform vec2 resolution;

void main() {
	vec2 pos = gl_FragCoord.xy/resolution.y;
	pos.x -= resolution.x/resolution.y/2.0;
	pos.y -= 0.5;
	float t = mod(time, 8.);
	float fx = sin(pos.x*10.0+t*BLU_SPEED++BLU_SPEED*2.0)/4.0;
	float dist = abs(pos.y-fx)*80.0;
	gl_FragColor = vec4(0.5/dist,0.5/dist,1.0/dist,1.0);
}
```

Except it wouldn't. Let this run for a couple of minutes and time will get big enough to make the animation jump (or look like the frame count has gone down).

So what to do? Maybe the only option is to use time in a way that does not need to be precise?

**Comment by xloem** [comment]
That ftime build is great.  Here's the shader changed to work on it.  I'm sorry for the formatting, I'm on a phone:

precision mediump float;

#define PI 3.141592653589793238
#define BLU_PERIOD 4 /*integer speeds only*/

uniform float time;
int itime = int(time);
uniform float ftime;
uniform vec2 resolution;

float timemod(int seconds)
{
	seconds = itime - (itime / seconds) * seconds; // = mod(itime, seconds)
	return float(seconds) + ftime;
}

void main() {
    vec2 pos = gl_FragCoord.xy/resolution.y;
    pos.x -= resolution.x/resolution.y/2.0;
    pos.y -= 0.5;
    float fx = sin(pos.x*10.0+timemod(BLU_PERIOD)*PI*2.0/float(BLU_PERIOD))/4.0;
		float dist = abs(pos.y-fx)*80.0;
    gl_FragColor = vec4(0.5/dist,0.5/dist,1.0/dist,1.0);
}

However, I'm not sure this is the best solution, as it limits one to animation periods that are integer multiples of a second.  I think a better a solution would be to provide a 'time' value that ranges between only 0.0 and 1.0, and in the settings let the user decide how fast it will advance.  Unfortunately this may break existing shaders.

**Comment by stuartpb** [comment]
The way I see it, there are a few approaches to solving this problem, each of which have merit and should be made available to shaders, where allowable by hardware restrictions.

The first one is to keep the time system as it is, for high-precision floats. This avoids breaking legacy shaders, and is "good enough" for some simple shaders / hardware environments. (I'd document that it's generally deprecated in favor of one of the more versatile approaches, though.)

The second is to implement a time measure split across two values, an integral count of seconds and a *separate float* for the fractional component of the second. (It seems that it'd possible to let the count of seconds be the *longest available integer type* rather than keeping it the same floating-point type as the fractional value; is there a GLSL reason why this can't be achieved?) As @markusfisch noted, this doesn't work if the shader attempts to *re-combine* these values; however, it's possible to write shaders in a form that considers the two components *separately*, and when doing so, this approach is a good solution (especially for shaders following irregular or complex intervals, eg. one involviong logartihmic growth or following the [cicada principle](https://www.sitepoint.com/the-cicada-principle-and-why-it-matters-to-web-designers/)).

The third is to have the shader define a value, as @xloem describes (though it need not necessarily be an integer) where all time values will be scaled to [0, 1) within that period; one of the things I like most about this approach is that it naturally lets such shaders be "sped up" or "slowed down" by simply adjusting the period value. Of course, this is still subject to problems with degraded precision if mapped to any long periods (eg. one where a cycle is 210 seconds), but the degradation would at least be distributed more evenly (stretching the higher-precision low fractions across a longer span of time).

As I said, I think the best solution would be to make *each* of these values available:

```glsl
/* legacy and/or non-portable shaders could use: */
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
/* straightforward but fragile implementation here */

#else
precision mediump float;

/* long-running/indefinite-period shaders would use: */

uniform int seconds;
uniform float subseconds;

/* two-step operation considering seconds and sub-seconds separately goes here */

/* short-period, smoothly-cycling shaders would use: */

#define FTIME_PERIOD 3.14
uniform float ftime;

/* code with a function that maps this value within a cycle goes here */

/* and, of course, somebody could write a shader that necessitates
   the use of *both* of these mechanisms, simultaneously */
#endif
```

**Comment by xloem** [comment]
A further option is to provide the number of milliseconds as an integer.  This should yield smooth animation for at least 65 and a half seconds (16 bits).  But that FTIME_PERIOD option looks the best to me.  It is intuitive to use, and the app could even scrape the value to pass the proper ftime in in advance.

**Comment by xloem** [comment]
Also: note that if ftime ranges between -1.0 and +1.0, one could squeeze twice as much precision out of it.

**Comment by markusfisch** [comment]
@xloem Clever solution! Works like a charm!

You're both right. If it's okay, I'll implement it like @stuartpb proposed (additional `second`, `subsecond` and `ftime` uniforms).

And since a mediump int (for the `second` uniform) ranges up to 1024, it'd take ~17 minutes before it wraps. More than enough I think.

**Comment by stuartpb** [comment]
> and the app could even scrape the value to pass the proper ftime in in advance.

That's what I was talking about - I don't know of another way to do it, as the `ftime` value can't work if the proper value isn't passed in initially.

**Comment by markusfisch** [comment]
Added `second` and `subsecond` uniforms and changed `ftime` to give a float between -1.0 to +1.0 within a cycle of 3.1415 seconds (see https://github.com/markusfisch/ShaderEditor/commit/90d649dffebf4c6d8bf4153638995fa7e6599b8d).

Also pushed that change into beta (should become available in the next hour or so), if you like to test it now:
https://play.google.com/apps/testing/de.markusfisch.android.shadereditor

**Comment by stuartpb** [comment]
Whoa whoa whoa whoa whoa, `fitme` is supposed to be *configurable by the shader* by defining a value for `FITME_PERIOD`! I just picked 3.14 in my example as an arbitrary floating-point value to demonstrate that this works for non-integer divisors - it's hardly a suitable time duration for any good animation.

**Comment by markusfisch** [comment]
Ah, okay, I see. Changed it accordingly in https://github.com/markusfisch/ShaderEditor/commit/d9e5e9bb4fe52df1341aaaedf6bb1623fa20a2e7. Now you can simply #define FTIME_PERIOD to set a period in seconds.

Should become available within the next hour or so in beta.
